name: Generate SBOM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install cdxgen
      run: npm install -g @cyclonedx/cdxgen

    - name: Generate SBOM
      run: cdxgen -r . -o bom.json
